// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Explore*
 */
export interface FooterDocumentDataExploreItem {
  /**
   * Heading field in *Footer → Explore*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.explore[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Explore Links field in *Footer → Explore*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.explore[].explore_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  explore_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * Heading field in *Footer → Socials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Social Links field in *Footer → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].social_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Contacts*
 */
export interface FooterDocumentDataContactsItem {
  /**
   * Heading field in *Footer → Contacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Telephone field in *Footer → Contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].telephone
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  telephone: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Email field in *Footer → Contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].email
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Short description field in *Footer → Contacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Address field in *Footer → Contacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].address
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;
}

/**
 * Item in *Footer → Legal Links*
 */
export interface FooterDocumentDataLegalLinksItem {
  /**
   * Terms and conditions field in *Footer → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[].terms_and_conditions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  terms_and_conditions: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Privacy and Cookies field in *Footer → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[].privacy_and_cookies
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_and_cookies: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Explore field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.explore[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  explore: prismic.GroupField<Simplify<FooterDocumentDataExploreItem>>;

  /**
   * Socials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;

  /**
   * Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<Simplify<FooterDocumentDataContactsItem>>;

  /**
   * Legal Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  legal_links: prismic.GroupField<Simplify<FooterDocumentDataLegalLinksItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Nav Links field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA Link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | SubmissionSectionSlice
  | FaQSlice
  | JuryPanelSlice
  | ReflectionSlice
  | LastYearWinnersSlice
  | HeroSectionSlice
  | EvaluationFrameworkSlice
  | AwardCategoriesSlice
  | ThePrizesSlice
  | PeopleChoiceAwardSlice
  | SectionThreeSlice
  | SecondSectionSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Event Date field in *Homepage*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Set your date here
   * - **API ID Path**: homepage.event_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  event_date: prismic.TimestampField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomepageDocument;

/**
 * Item in *AwardCategories → Default → Primary → Cards*
 */
export interface AwardCategoriesSliceDefaultPrimaryCardsItem {
  /**
   * Eyebrow Heading field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Eyebrow Heading Two field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].eyebrow_heading_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading_two: prismic.RichTextField;

  /**
   * Icon field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Card Heading field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * Short description field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Tags field in *AwardCategories → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[].tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;
}

/**
 * Primary content in *AwardCategories → Default → Primary*
 */
export interface AwardCategoriesSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Short description field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Cards field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<AwardCategoriesSliceDefaultPrimaryCardsItem>
  >;

  /**
   * Second Heading field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  second_heading: prismic.RichTextField;

  /**
   * Eligibilities field in *AwardCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award_categories.default.primary.eligibilities
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eligibilities: prismic.RichTextField;
}

/**
 * Default variation for AwardCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AwardCategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AwardCategoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AwardCategories*
 */
type AwardCategoriesSliceVariation = AwardCategoriesSliceDefault;

/**
 * AwardCategories Shared Slice
 *
 * - **API ID**: `award_categories`
 * - **Description**: AwardCategories
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AwardCategoriesSlice = prismic.SharedSlice<
  "award_categories",
  AwardCategoriesSliceVariation
>;

/**
 * Item in *EvaluationFramework → Default → Primary → Image And Link*
 */
export interface EvaluationFrameworkSliceDefaultPrimaryImageAndLinkItem {
  /**
   * Image field in *EvaluationFramework → Default → Primary → Image And Link*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.image_and_link[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *EvaluationFramework → Default → Primary → Image And Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.image_and_link[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *EvaluationFramework → Default → Primary → Cards*
 */
export interface EvaluationFrameworkSliceDefaultPrimaryCardsItem {
  /**
   * Percentage  field in *EvaluationFramework → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.cards[].percentage
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  percentage: prismic.RichTextField;

  /**
   * Card Heading field in *EvaluationFramework → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * Card description field in *EvaluationFramework → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.cards[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_description: prismic.RichTextField;
}

/**
 * Primary content in *EvaluationFramework → Default → Primary*
 */
export interface EvaluationFrameworkSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Description field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image And Link field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.image_and_link[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  image_and_link: prismic.GroupField<
    Simplify<EvaluationFrameworkSliceDefaultPrimaryImageAndLinkItem>
  >;

  /**
   * Cards field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<EvaluationFrameworkSliceDefaultPrimaryCardsItem>
  >;

  /**
   * Bottom Description field in *EvaluationFramework → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evaluation_framework.default.primary.bottom_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bottom_description: prismic.RichTextField;
}

/**
 * Default variation for EvaluationFramework Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EvaluationFrameworkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EvaluationFrameworkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EvaluationFramework*
 */
type EvaluationFrameworkSliceVariation = EvaluationFrameworkSliceDefault;

/**
 * EvaluationFramework Shared Slice
 *
 * - **API ID**: `evaluation_framework`
 * - **Description**: EvaluationFramework
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EvaluationFrameworkSlice = prismic.SharedSlice<
  "evaluation_framework",
  EvaluationFrameworkSliceVariation
>;

/**
 * Item in *FaQ → Default → Primary → FaQs*
 */
export interface FaQSliceDefaultPrimaryFaqsItem {
  /**
   * Title field in *FaQ → Default → Primary → FaQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faqs[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Info field in *FaQ → Default → Primary → FaQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faqs[].info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  info: prismic.RichTextField;
}

/**
 * Primary content in *FaQ → Default → Primary*
 */
export interface FaQSliceDefaultPrimary {
  /**
   * Main Heading field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Description field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * FaQs field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaQSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for FaQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaQSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaQSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaQ*
 */
type FaQSliceVariation = FaQSliceDefault;

/**
 * FaQ Shared Slice
 *
 * - **API ID**: `fa_q`
 * - **Description**: FaQ
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaQSlice = prismic.SharedSlice<"fa_q", FaQSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Eyebrow Heading Two field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.eyebrow_heading_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading_two: prismic.RichTextField;

  /**
   * Main Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Short description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Button One field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter button text on "Display Text"
   * - **API ID Path**: hero_section.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Two field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *JuryPanel → Default → Primary → Jury Cards*
 */
export interface JuryPanelSliceDefaultPrimaryJuryCardsItem {
  /**
   * Image field in *JuryPanel → Default → Primary → Jury Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.jury_cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *JuryPanel → Default → Primary → Jury Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.jury_cards[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Title field in *JuryPanel → Default → Primary → Jury Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.jury_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Company field in *JuryPanel → Default → Primary → Jury Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.jury_cards[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;
}

/**
 * Primary content in *JuryPanel → Default → Primary*
 */
export interface JuryPanelSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *JuryPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *JuryPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Short description field in *JuryPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Jury Cards field in *JuryPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_panel.default.primary.jury_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  jury_cards: prismic.GroupField<
    Simplify<JuryPanelSliceDefaultPrimaryJuryCardsItem>
  >;
}

/**
 * Default variation for JuryPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JuryPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JuryPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JuryPanel*
 */
type JuryPanelSliceVariation = JuryPanelSliceDefault;

/**
 * JuryPanel Shared Slice
 *
 * - **API ID**: `jury_panel`
 * - **Description**: JuryPanel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JuryPanelSlice = prismic.SharedSlice<
  "jury_panel",
  JuryPanelSliceVariation
>;

/**
 * Item in *LastYearWinners → Default → Primary → CategoryOne*
 */
export interface LastYearWinnersSliceDefaultPrimaryCategoryoneItem {
  /**
   * Image field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Country field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Text
   * - **Placeholder**: India, Spain or Netherlands
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].country
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country: prismic.KeyTextField;

  /**
   * Position field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Name field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Project field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].project
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project: prismic.RichTextField;

  /**
   * Description field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Learn More field in *LastYearWinners → Default → Primary → CategoryOne*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[].learn_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  learn_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *LastYearWinners → Default → Primary → Category Two*
 */
export interface LastYearWinnersSliceDefaultPrimaryCategoryTwoItem {
  /**
   * Image field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Country field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].country
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country: prismic.KeyTextField;

  /**
   * Position field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Name field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Project field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].project
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project: prismic.RichTextField;

  /**
   * Description field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Link field in *LastYearWinners → Default → Primary → Category Two*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *LastYearWinners → Default → Primary*
 */
export interface LastYearWinnersSliceDefaultPrimary {
  /**
   * Main Heading field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Short description field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Cateory One Title field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.cateory_one_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cateory_one_title: prismic.RichTextField;

  /**
   * CategoryOne field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.categoryone[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categoryone: prismic.GroupField<
    Simplify<LastYearWinnersSliceDefaultPrimaryCategoryoneItem>
  >;

  /**
   * Category Two Title field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  category_two_title: prismic.RichTextField;

  /**
   * Category Two field in *LastYearWinners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: last_year_winners.default.primary.category_two[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  category_two: prismic.GroupField<
    Simplify<LastYearWinnersSliceDefaultPrimaryCategoryTwoItem>
  >;
}

/**
 * Default variation for LastYearWinners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LastYearWinnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LastYearWinnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LastYearWinners*
 */
type LastYearWinnersSliceVariation = LastYearWinnersSliceDefault;

/**
 * LastYearWinners Shared Slice
 *
 * - **API ID**: `last_year_winners`
 * - **Description**: LastYearWinners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LastYearWinnersSlice = prismic.SharedSlice<
  "last_year_winners",
  LastYearWinnersSliceVariation
>;

/**
 * Primary content in *PeopleChoiceAward → Default → Primary*
 */
export interface PeopleChoiceAwardSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *PeopleChoiceAward → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_choice_award.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *PeopleChoiceAward → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_choice_award.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Description field in *PeopleChoiceAward → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_choice_award.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PeopleChoiceAward Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleChoiceAwardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PeopleChoiceAwardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PeopleChoiceAward*
 */
type PeopleChoiceAwardSliceVariation = PeopleChoiceAwardSliceDefault;

/**
 * PeopleChoiceAward Shared Slice
 *
 * - **API ID**: `people_choice_award`
 * - **Description**: PeopleChoiceAward
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleChoiceAwardSlice = prismic.SharedSlice<
  "people_choice_award",
  PeopleChoiceAwardSliceVariation
>;

/**
 * Item in *Reflection → Default → Primary → Categories*
 */
export interface ReflectionSliceDefaultPrimaryCategoriesItem {
  /**
   * Icon field in *Reflection → Default → Primary → Categories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.categories[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Reflection → Default → Primary → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.categories[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Short description field in *Reflection → Default → Primary → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.categories[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;
}

/**
 * Primary content in *Reflection → Default → Primary*
 */
export interface ReflectionSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *Reflection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *Reflection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Description field in *Reflection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Quote field in *Reflection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Categories field in *Reflection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reflection.default.primary.categories[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<
    Simplify<ReflectionSliceDefaultPrimaryCategoriesItem>
  >;
}

/**
 * Default variation for Reflection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReflectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReflectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Reflection*
 */
type ReflectionSliceVariation = ReflectionSliceDefault;

/**
 * Reflection Shared Slice
 *
 * - **API ID**: `reflection`
 * - **Description**: Reflection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReflectionSlice = prismic.SharedSlice<
  "reflection",
  ReflectionSliceVariation
>;

/**
 * Primary content in *SecondSection → Default → Primary*
 */
export interface SecondSectionSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *SecondSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *SecondSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Description field in *SecondSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Quote Field field in *SecondSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.default.primary.quote_field
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote_field: prismic.RichTextField;
}

/**
 * Default variation for SecondSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SecondSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecondSection*
 */
type SecondSectionSliceVariation = SecondSectionSliceDefault;

/**
 * SecondSection Shared Slice
 *
 * - **API ID**: `second_section`
 * - **Description**: SecondSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SecondSectionSlice = prismic.SharedSlice<
  "second_section",
  SecondSectionSliceVariation
>;

/**
 * Item in *SectionThree → Default → Primary → Content Columns*
 */
export interface SectionThreeSliceDefaultPrimaryContentColumnsItem {
  /**
   * Icon field in *SectionThree → Default → Primary → Content Columns*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_three.default.primary.content_columns[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *SectionThree → Default → Primary → Content Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_three.default.primary.content_columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SectionThree → Default → Primary → Content Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_three.default.primary.content_columns[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *SectionThree → Default → Primary*
 */
export interface SectionThreeSliceDefaultPrimary {
  /**
   * Main Heading field in *SectionThree → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_three.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Content Columns field in *SectionThree → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_three.default.primary.content_columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  content_columns: prismic.GroupField<
    Simplify<SectionThreeSliceDefaultPrimaryContentColumnsItem>
  >;
}

/**
 * Default variation for SectionThree Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionThreeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionThreeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionThree*
 */
type SectionThreeSliceVariation = SectionThreeSliceDefault;

/**
 * SectionThree Shared Slice
 *
 * - **API ID**: `section_three`
 * - **Description**: SectionThree
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionThreeSlice = prismic.SharedSlice<
  "section_three",
  SectionThreeSliceVariation
>;

/**
 * Item in *SubmissionSection → Default → Primary → Top Section*
 */
export interface SubmissionSectionSliceDefaultPrimaryTopSectionItem {
  /**
   * Eyebrow Heading field in *SubmissionSection → Default → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_section[].eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Heading field in *SubmissionSection → Default → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_section[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Short description field in *SubmissionSection → Default → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_section[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Button field in *SubmissionSection → Default → Primary → Top Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_section[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *SubmissionSection → Default → Primary → Top Right Card*
 */
export interface SubmissionSectionSliceDefaultPrimaryTopRightCardItem {
  /**
   * Title field in *SubmissionSection → Default → Primary → Top Right Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_right_card[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Info field in *SubmissionSection → Default → Primary → Top Right Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_right_card[].info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  info: prismic.RichTextField;
}

/**
 * Item in *SubmissionSection → Default → Primary → Bottom Section*
 */
export interface SubmissionSectionSliceDefaultPrimaryBottomSectionItem {
  /**
   * Eyebrow Heading field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Eyebrow Heading Two field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].eyebrow_heading_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading_two: prismic.RichTextField;

  /**
   * Heading field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * Description field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Last Date field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[].last_date
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  last_date: prismic.RichTextField;

  /**
   * Button One field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Text
   * - **API ID Path**: submission_section.default.primary.bottom_section[].button_one
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_one: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Two field in *SubmissionSection → Default → Primary → Bottom Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Text
   * - **API ID Path**: submission_section.default.primary.bottom_section[].button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *SubmissionSection → withVideo → Primary → Top Section*
 */
export interface SubmissionSectionSliceWithVideoPrimaryTopSectionItem {
  /**
   * Eyebrow Heading field in *SubmissionSection → withVideo → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[].eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Heading field in *SubmissionSection → withVideo → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Short description field in *SubmissionSection → withVideo → Primary → Top Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Button field in *SubmissionSection → withVideo → Primary → Top Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Small Image field in *SubmissionSection → withVideo → Primary → Top Section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[].small_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  small_image: prismic.ImageField<never>;
}

/**
 * Item in *SubmissionSection → withVideo → Primary → Top Right Card*
 */
export interface SubmissionSectionSliceWithVideoPrimaryTopRightCardItem {
  /**
   * Embed Link field in *SubmissionSection → withVideo → Primary → Top Right Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_right_card[].embed_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  embed_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *SubmissionSection → withVideo → Primary → Top Right Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description under the video
   * - **API ID Path**: submission_section.withVideo.primary.top_right_card[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *SubmissionSection → withVideo → Primary → Bottom Section*
 */
export interface SubmissionSectionSliceWithVideoPrimaryBottomSectionItem {
  /**
   * Eyebrow Heading field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Eyebrow Heading Two field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].eyebrow_heading_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading_two: prismic.RichTextField;

  /**
   * Heading field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * Description field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Last Date field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].last_date
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  last_date: prismic.RichTextField;

  /**
   * Button One field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Text
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].button_one
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_one: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Two field in *SubmissionSection → withVideo → Primary → Bottom Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Text
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[].button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SubmissionSection → Default → Primary*
 */
export interface SubmissionSectionSliceDefaultPrimary {
  /**
   * Top Section field in *SubmissionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  top_section: prismic.GroupField<
    Simplify<SubmissionSectionSliceDefaultPrimaryTopSectionItem>
  >;

  /**
   * Top Right Card field in *SubmissionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.top_right_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  top_right_card: prismic.GroupField<
    Simplify<SubmissionSectionSliceDefaultPrimaryTopRightCardItem>
  >;

  /**
   * Bottom Section field in *SubmissionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.default.primary.bottom_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bottom_section: prismic.GroupField<
    Simplify<SubmissionSectionSliceDefaultPrimaryBottomSectionItem>
  >;
}

/**
 * Default variation for SubmissionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubmissionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubmissionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SubmissionSection → withVideo → Primary*
 */
export interface SubmissionSectionSliceWithVideoPrimary {
  /**
   * Top Section field in *SubmissionSection → withVideo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  top_section: prismic.GroupField<
    Simplify<SubmissionSectionSliceWithVideoPrimaryTopSectionItem>
  >;

  /**
   * Top Right Card field in *SubmissionSection → withVideo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.top_right_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  top_right_card: prismic.GroupField<
    Simplify<SubmissionSectionSliceWithVideoPrimaryTopRightCardItem>
  >;

  /**
   * Bottom Section field in *SubmissionSection → withVideo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_section.withVideo.primary.bottom_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bottom_section: prismic.GroupField<
    Simplify<SubmissionSectionSliceWithVideoPrimaryBottomSectionItem>
  >;
}

/**
 * withVideo variation for SubmissionSection Slice
 *
 * - **API ID**: `withVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubmissionSectionSliceWithVideo = prismic.SharedSliceVariation<
  "withVideo",
  Simplify<SubmissionSectionSliceWithVideoPrimary>,
  never
>;

/**
 * Slice variation for *SubmissionSection*
 */
type SubmissionSectionSliceVariation =
  | SubmissionSectionSliceDefault
  | SubmissionSectionSliceWithVideo;

/**
 * SubmissionSection Shared Slice
 *
 * - **API ID**: `submission_section`
 * - **Description**: SubmissionSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubmissionSectionSlice = prismic.SharedSlice<
  "submission_section",
  SubmissionSectionSliceVariation
>;

/**
 * Item in *ThePrizes → Default → Primary → Categories*
 */
export interface ThePrizesSliceDefaultPrimaryCategoriesItem {
  /**
   * Medal Icon field in *ThePrizes → Default → Primary → Categories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.categories[].medal_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  medal_icon: prismic.ImageField<never>;

  /**
   * Position field in *ThePrizes → Default → Primary → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.categories[].position
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  position: prismic.RichTextField;

  /**
   * Bullet Points field in *ThePrizes → Default → Primary → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.categories[].bullet_points
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bullet_points: prismic.RichTextField;
}

/**
 * Primary content in *ThePrizes → Default → Primary*
 */
export interface ThePrizesSliceDefaultPrimary {
  /**
   * Eyebrow Heading field in *ThePrizes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.eyebrow_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow_heading: prismic.RichTextField;

  /**
   * Main Heading field in *ThePrizes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Short description field in *ThePrizes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Categories field in *ThePrizes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: the_prizes.default.primary.categories[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<
    Simplify<ThePrizesSliceDefaultPrimaryCategoriesItem>
  >;
}

/**
 * Default variation for ThePrizes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThePrizesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThePrizesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThePrizes*
 */
type ThePrizesSliceVariation = ThePrizesSliceDefault;

/**
 * ThePrizes Shared Slice
 *
 * - **API ID**: `the_prizes`
 * - **Description**: ThePrizes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThePrizesSlice = prismic.SharedSlice<
  "the_prizes",
  ThePrizesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataExploreItem,
      FooterDocumentDataSocialsItem,
      FooterDocumentDataContactsItem,
      FooterDocumentDataLegalLinksItem,
      HeaderDocument,
      HeaderDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AwardCategoriesSlice,
      AwardCategoriesSliceDefaultPrimaryCardsItem,
      AwardCategoriesSliceDefaultPrimary,
      AwardCategoriesSliceVariation,
      AwardCategoriesSliceDefault,
      EvaluationFrameworkSlice,
      EvaluationFrameworkSliceDefaultPrimaryImageAndLinkItem,
      EvaluationFrameworkSliceDefaultPrimaryCardsItem,
      EvaluationFrameworkSliceDefaultPrimary,
      EvaluationFrameworkSliceVariation,
      EvaluationFrameworkSliceDefault,
      FaQSlice,
      FaQSliceDefaultPrimaryFaqsItem,
      FaQSliceDefaultPrimary,
      FaQSliceVariation,
      FaQSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      JuryPanelSlice,
      JuryPanelSliceDefaultPrimaryJuryCardsItem,
      JuryPanelSliceDefaultPrimary,
      JuryPanelSliceVariation,
      JuryPanelSliceDefault,
      LastYearWinnersSlice,
      LastYearWinnersSliceDefaultPrimaryCategoryoneItem,
      LastYearWinnersSliceDefaultPrimaryCategoryTwoItem,
      LastYearWinnersSliceDefaultPrimary,
      LastYearWinnersSliceVariation,
      LastYearWinnersSliceDefault,
      PeopleChoiceAwardSlice,
      PeopleChoiceAwardSliceDefaultPrimary,
      PeopleChoiceAwardSliceVariation,
      PeopleChoiceAwardSliceDefault,
      ReflectionSlice,
      ReflectionSliceDefaultPrimaryCategoriesItem,
      ReflectionSliceDefaultPrimary,
      ReflectionSliceVariation,
      ReflectionSliceDefault,
      SecondSectionSlice,
      SecondSectionSliceDefaultPrimary,
      SecondSectionSliceVariation,
      SecondSectionSliceDefault,
      SectionThreeSlice,
      SectionThreeSliceDefaultPrimaryContentColumnsItem,
      SectionThreeSliceDefaultPrimary,
      SectionThreeSliceVariation,
      SectionThreeSliceDefault,
      SubmissionSectionSlice,
      SubmissionSectionSliceDefaultPrimaryTopSectionItem,
      SubmissionSectionSliceDefaultPrimaryTopRightCardItem,
      SubmissionSectionSliceDefaultPrimaryBottomSectionItem,
      SubmissionSectionSliceDefaultPrimary,
      SubmissionSectionSliceWithVideoPrimaryTopSectionItem,
      SubmissionSectionSliceWithVideoPrimaryTopRightCardItem,
      SubmissionSectionSliceWithVideoPrimaryBottomSectionItem,
      SubmissionSectionSliceWithVideoPrimary,
      SubmissionSectionSliceVariation,
      SubmissionSectionSliceDefault,
      SubmissionSectionSliceWithVideo,
      ThePrizesSlice,
      ThePrizesSliceDefaultPrimaryCategoriesItem,
      ThePrizesSliceDefaultPrimary,
      ThePrizesSliceVariation,
      ThePrizesSliceDefault,
    };
  }
}
