// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  award_categories: dynamic(() => import("./AwardCategories")),
  evaluation_framework: dynamic(() => import("./EvaluationFramework")),
  fa_q: dynamic(() => import("./FaQ")),
  hero_section: dynamic(() => import("./HeroSection")),
  jury_panel: dynamic(() => import("./JuryPanel")),
  last_year_winners: dynamic(() => import("./LastYearWinners")),
  people_choice_award: dynamic(() => import("./PeopleChoiceAward")),
  reflection: dynamic(() => import("./Reflection")),
  second_section: dynamic(() => import("./SecondSection")),
  section_three: dynamic(() => import("./SectionThree")),
  submission_section: dynamic(() => import("./SubmissionSection")),
  the_prizes: dynamic(() => import("./ThePrizes")),
};
